---
  version: "3.3"
  services:
    app:
      restart: always
      image: sewliothewise/insomnia_survey:latest
      ports:                                    
        - "4000:4000"
      environment:
        - MONGO_HOST=mongo   
      depends_on:
        - mongo
    mongo:
      image: mongo
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - ./mongo-db:/data/db
